tap "keith/formulae"
tap "peripheryapp/periphery"
tap "withgraphite/tap"
tap "xcodesorg/made"

# CLI tools
brew "aria2"
brew "cloc"
brew "gh"
brew "git-lfs"
brew "jq"
brew "lazygit"
brew "mise"
brew "navi"
brew "neovim"
brew "node@18"
brew "pup"
brew "rbenv"
brew "ruby-build"
brew "rsync"
brew "ruby@3.2"
brew "the_silver_searcher"
brew "tmux"
brew "uv"
brew "wget"
brew "zoxide"
brew "zplug"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

# iOS/macOS dev
brew "cocoapods"
brew "fastlane"
brew "swiftlint"
brew "xcodesorg/made/xcodes"

# Other
brew "bazel"
brew "nginx"
brew "wabt"
brew "zig"
brew "withgraphite/tap/graphite"
brew "keith/formulae/ld64.lld"

# Casks
cask "charles"
cask "font-fira-code"
cask "ghostty"
cask "obsidian"
cask "peripheryapp/periphery/periphery"
cask "rocket"
cask "xcodes-app"

# VS Code extensions (non-Amazon)
vscode "bierner.markdown-mermaid"
vscode "davidanson.vscode-markdownlint"
vscode "eamodio.gitlens"
vscode "graphite.gti-vscode"
vscode "jebbs.plantuml"
vscode "mechatroner.rainbow-csv"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-vscode.cmake-tools"
vscode "ms-vscode.cpptools"
vscode "ms-vscode.cpptools-extension-pack"
vscode "swiftlang.swift-vscode"
